#include <unordered_map>
#include "symbol.h"

std::unordered_map<std::string, int> const_val; // To record the value of the value
std::unordered_map<std::string, TYPE> var_type; // To record the type of the value
int blk_idx = 0;
int now_idx = 0;
int block_tree[1000]={0};

int if_idx = 0; // to identify the block generated by jump
int if_dep = 0; // to identify the basic block
int now_if_dep = 0;
int end_blk[1000]={0}; // to record if there are jump statement
int while_idx = 0;
int while_block[1000]={0};
int now_while_idx = 0;